import type { AIArchetype, AIStyle } from "./types.ts";

/**
 * Persona tuning mirrors the native app's five learning profiles. Values are
 * intentionally kept here, outside React and the poker rules engine.
 */
export const AI_STYLE_PROFILES: Record<AIArchetype, AIStyle> = {
  "tight-aggressive": {
    key: "tight-aggressive",
    label: "紧凶",
    summary: "耐心等价值牌，入池后主动施压",
    aggression: 0.72,
    looseness: 0.3,
    aggressiveThreshold: 0.6,
    passiveThreshold: 0.32,
    aggressionChance: 0.88,
    continueChance: 0.82,
    bluffThreshold: 0.24,
    bluffChance: 0.1,
    learningRate: 0.3,
    memoryWindow: 50,
    adjustmentCap: 0.15,
    initialExploration: 0.3,
    minimumExploration: 0.05,
    explorationDecay: 0.8,
    aggressiveLearningWeight: 1.1,
    passiveLearningWeight: 0.9,
    foldLearningWeight: 1,
    thinkingPace: 1.08,
    tankChance: 0.17,
  },
  "loose-aggressive": {
    key: "loose-aggressive",
    label: "松凶",
    summary: "宽范围入池，频繁抢夺主动权",
    aggression: 0.86,
    looseness: 0.72,
    aggressiveThreshold: 0.42,
    passiveThreshold: 0.2,
    aggressionChance: 0.82,
    continueChance: 0.76,
    bluffThreshold: 0.12,
    bluffChance: 0.34,
    learningRate: 0.5,
    memoryWindow: 30,
    adjustmentCap: 0.3,
    initialExploration: 0.4,
    minimumExploration: 0.1,
    explorationDecay: 0.85,
    aggressiveLearningWeight: 1.28,
    passiveLearningWeight: 0.88,
    foldLearningWeight: 0.86,
    thinkingPace: 0.76,
    tankChance: 0.08,
  },
  "tight-weak": {
    key: "tight-weak",
    label: "紧弱",
    summary: "选牌谨慎，面对压力更倾向控池",
    aggression: 0.2,
    looseness: 0.24,
    aggressiveThreshold: 0.8,
    passiveThreshold: 0.62,
    aggressionChance: 0.18,
    continueChance: 0.88,
    bluffThreshold: 0.18,
    bluffChance: 0.02,
    learningRate: 0.1,
    memoryWindow: 20,
    adjustmentCap: 0.05,
    initialExploration: 0.2,
    minimumExploration: 0.05,
    explorationDecay: 0.9,
    aggressiveLearningWeight: 0.72,
    passiveLearningWeight: 1.05,
    foldLearningWeight: 1.18,
    thinkingPace: 1.18,
    tankChance: 0.24,
  },
  "loose-weak": {
    key: "loose-weak",
    label: "跟注站",
    summary: "看牌范围很宽，喜欢跟注到后面",
    aggression: 0.08,
    looseness: 0.82,
    aggressiveThreshold: 0.72,
    passiveThreshold: 0.28,
    aggressionChance: 0.08,
    continueChance: 0.92,
    bluffThreshold: 0.1,
    bluffChance: 0.06,
    learningRate: 0.05,
    memoryWindow: 10,
    adjustmentCap: 0.03,
    initialExploration: 0.35,
    minimumExploration: 0.15,
    explorationDecay: 0.9,
    aggressiveLearningWeight: 0.62,
    passiveLearningWeight: 1,
    foldLearningWeight: 0.92,
    thinkingPace: 0.9,
    tankChance: 0.12,
  },
  balanced: {
    key: "balanced",
    label: "均衡",
    summary: "根据位置、牌面和对手动态换挡",
    aggression: 0.58,
    looseness: 0.54,
    aggressiveThreshold: 0.52,
    passiveThreshold: 0.26,
    aggressionChance: 0.58,
    continueChance: 0.72,
    bluffThreshold: 0.18,
    bluffChance: 0.18,
    learningRate: 0.4,
    memoryWindow: 60,
    adjustmentCap: 0.25,
    initialExploration: 0.3,
    minimumExploration: 0.08,
    explorationDecay: 0.82,
    aggressiveLearningWeight: 1,
    passiveLearningWeight: 1,
    foldLearningWeight: 1,
    thinkingPace: 0.98,
    tankChance: 0.2,
  },
};

const STYLE_BY_PLAYER_ID: Record<number, AIArchetype> = {
  1: "tight-aggressive",
  2: "loose-aggressive",
  3: "tight-weak",
  4: "loose-weak",
  5: "balanced",
};

export function aiStyleForPlayerId(playerId: number): AIStyle {
  return AI_STYLE_PROFILES[STYLE_BY_PLAYER_ID[playerId] ?? "balanced"];
}
